DEFAULTVAL_TYPES = {
    "0": {"input_types": ["list"], "output_types": ["float"]},
    "1": {"input_types": ["int"], "output_types": ["dict"]},
    "2": {"input_types": ["list"], "output_types": ["dict"]},
    "3": {"input_types": ["list"], "output_types": ["dict"]},
    "4": {"input_types": ["dict"], "output_types": ["dict"]},
    "5": {"input_types": ["list"], "output_types": ["dict"]},
    "6": {"input_types": ["str", "str"], "output_types": ["str", "None"]},
    "7": {"input_types": ["str"], "output_types": ["str"]},
    "8": {"input_types": ["tuple", "int"], "output_types": ["Counter"]},
    "9": {"input_types": ["list"], "output_types": ["tuple", "DataFrame", "Axes"]},
    "10": {"input_types": ["tuple", "int"], "output_types": ["tuple"]},
    "11": {"input_types": ["tuple", "int"], "output_types": ["tuple"]},
    "12": {"input_types": ["str", "str"], "output_types": ["dict"]},
    "13": {"input_types": ["str", "str", "str", "str"], "output_types": ["list"]},
    "14": {"input_types": ["str", "str"], "output_types": ["bool"]},
    "15": {"input_types": ["str", "str"], "output_types": ["list"]},
    "16": {"input_types": ["str", "str"], "output_types": ["str"]},
    "17": {"input_types": ["str"], "output_types": ["str"]},
    "18": {"input_types": ["str"], "output_types": ["list"]},
    "19": {"input_types": ["str"], "output_types": ["str"]},
    "20": {"input_types": ["str"], "output_types": ["tuple"]},
    "21": {"input_types": ["None"], "output_types": ["dict"]},
    "22": {"input_types": ["list", "list", "int"], "output_types": ["collections.Counter"]},
    "23": {"input_types": ["list", "list", "float"], "output_types": ["float"]},
    "24": {"input_types": ["str", "int"], "output_types": ["tuple"]},
    "25": {"input_types": ["dict"], "output_types": ["str"]},
    "26": {"input_types": ["str", "str"], "output_types": ["str"]},
    "27": {"input_types": ["dict"], "output_types": ["str"]},
    "28": {"input_types": ["dict", "str"], "output_types": ["requests.Response"]},
    "29": {"input_types": ["numpy.ndarray"], "output_types": ["str"]},
    "30": {"input_types": ["str", "str", "dict", "str"], "output_types": ["Any"]},
    "31": {"input_types": ["str"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "32": {"input_types": ["str", "str"], "output_types": ["str"]},
    "33": {"input_types": ["list"], "output_types": ["numpy.ndarray"]},
    "34": {"input_types": ["str"], "output_types": ["WordCloud"]},
    "35": {"input_types": ["DataFrame", "list"], "output_types": ["Axes"]},
    "36": {"input_types": ["pandas.DataFrame"], "output_types": ["pandas.DataFrame", "matplotlib.figure.Figure"]},
    "37": {
        "input_types": ["pandas.DataFrame", "str"],
        "output_types": ["sklearn.model.RandomForestClassifier", "matplotlib.axes.Axes"],
    },
    "38": {"input_types": ["numpy.array"], "output_types": ["tuple", "pandas.DataFrame", "matplotlib.axes.Axes"]},
    "39": {"input_types": ["numpy.array"], "output_types": ["tuple", "list", "Axes"]},
    "40": {"input_types": ["numpy.array"], "output_types": ["tuple", "pandas.DataFrame", "matplotlib.axes.Axes"]},
    "41": {"input_types": ["numpy.array"], "output_types": ["pandas.DataFrame", "matplotlib.axes.Axes"]},
    "42": {"input_types": ["numpy.array"], "output_types": ["tuple", "pandas.DataFrame", "matplotlib.axes._axes.Axes"]},
    "43": {"input_types": ["DataFrame"], "output_types": ["tuple", "DataFrame", "List[Axes]"]},
    "44": {"input_types": ["DataFrame"], "output_types": ["DataFrame", "Axes"]},
    "45": {"input_types": ["DataFrame"], "output_types": ["DataFrame", "Axes"]},
    "46": {"input_types": ["pandas.DataFrame"], "output_types": ["tuple"]},
    "47": {"input_types": ["pandas.DataFrame"], "output_types": ["pandas.DataFrame", "Axes"]},
    "48": {"input_types": ["int", "str"], "output_types": ["list"]},
    "49": {"input_types": ["list"], "output_types": ["pandas.DataFrame", "Axes"]},
    "50": {"input_types": ["int"], "output_types": ["tuple", "DataFrame", "Axes"]},
    "51": {"input_types": ["DataFrame", "int", "int"], "output_types": ["DataFrame", "Axes"]},
    "52": {"input_types": ["str"], "output_types": ["Series"]},
    "53": {"input_types": ["str"], "output_types": ["DataFrame"]},
    "54": {"input_types": ["str"], "output_types": ["DataFrame"]},
    "55": {"input_types": ["str"], "output_types": ["pandas.core.series.Series"]},
    "56": {"input_types": ["str"], "output_types": ["DataFrame"]},
    "57": {"input_types": ["str", "str"], "output_types": ["DataFrame", "matplotlib.axes.Axes"]},
    "58": {"input_types": ["float", "float", "int"], "output_types": ["matplotlib.figure.Figure"]},
    "59": {"input_types": ["str"], "output_types": ["matplotlib.axes.Axes"]},
    "60": {"input_types": ["list", "str", "str"], "output_types": ["None"]},
    "61": {"input_types": ["list"], "output_types": ["numpy.ndarray", "matplotlib.axes.Axes"]},
    "62": {"input_types": ["list", "list"], "output_types": ["None"]},
    "63": {"input_types": ["dict"], "output_types": ["tuple", "DataFrame", "Axes"]},
    "64": {"input_types": ["list"], "output_types": ["tuple", "pandas.DataFrame", "plt.Axes"]},
    "65": {"input_types": ["pandas.DataFrame"], "output_types": ["tuple", "pandas.DataFrame", "plt.Axes"]},
    "66": {"input_types": ["list"], "output_types": ["tuple", "pandas.DataFrame", "plt.Axes"]},
    "67": {"input_types": ["str", "str"], "output_types": ["pandas.DataFrame"]},
    "68": {"input_types": ["str", "str"], "output_types": ["DataFrame", "Axes"]},
    "69": {"input_types": ["dict"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "70": {"input_types": ["str"], "output_types": ["tuple"]},
    "71": {"input_types": ["str"], "output_types": ["tuple"]},
    "72": {"input_types": ["str"], "output_types": ["pandas.DataFrame", "matplotlib.axes._axes.Axes"]},
    "73": {"input_types": ["str"], "output_types": ["tuple", "DataFrame", "Axes"]},
    "74": {"input_types": ["str"], "output_types": ["dict"]},
    "75": {"input_types": ["pd.DataFrame", "list", "list", "int", "int", "int"], "output_types": ["tuple"]},
    "76": {"input_types": ["django.http.HttpRequest", "int"], "output_types": ["django.http.HttpResponse"]},
    "77": {"input_types": ["dict"], "output_types": ["django.http.HttpResponse"]},
    "78": {"input_types": ["HttpRequest", "list", "list"], "output_types": ["FileResponse"]},
    "79": {"input_types": ["HttpRequest", "list"], "output_types": ["FileResponse"]},
    "80": {"input_types": ["str"], "output_types": ["flask.app.Flask"]},
    "81": {"input_types": ["str", "str"], "output_types": ["Flask"]},
    "82": {"input_types": ["str", "str"], "output_types": ["Flask"]},
    "83": {"input_types": ["str", "int", "str", "str", "str"], "output_types": ["Flask"]},
    "84": {"input_types": ["list", "int", "int", "int", "float", "float", "int"], "output_types": ["pd.DataFrame"]},
    "85": {"input_types": ["datetime", "datetime", "int"], "output_types": ["DataFrame", "Axes"]},
    "86": {"input_types": ["list", "int"], "output_types": ["DataFrame", "Axes"]},
    "87": {"input_types": ["list", "list", "list", "int"], "output_types": ["pandas.DataFrame"]},
    "88": {"input_types": ["datetime", "datetime", "int"], "output_types": ["DataFrame", "Axes"]},
    "89": {"input_types": ["ndarray", "int", "float"], "output_types": ["tuple"]},
    "90": {"input_types": ["DataFrame", "list", "int"], "output_types": ["list"]},
    "91": {"input_types": ["DataFrame", "str", "str"], "output_types": ["tuple", "Axes"]},
    "92": {"input_types": ["pd.DataFrame", "int"], "output_types": ["tuple", "np.ndarray", "plt.Axes"]},
    "93": {"input_types": ["DataFrame", "int"], "output_types": ["DataFrame", "Axes"]},
    "94": {
        "input_types": ["float", "float", "int"],
        "output_types": ["tuple", "matplotlib.figure.Figure", "numpy.ndarray"],
    },
    "95": {"input_types": ["list", "list", "int"], "output_types": ["pandas.DataFrame"]},
    "96": {"input_types": ["str", "str"], "output_types": ["list"]},
    "97": {"input_types": ["list"], "output_types": ["float"]},
    "98": {"input_types": ["int", "int"], "output_types": ["list"]},
    "99": {"input_types": ["None"], "output_types": ["plt.Figure"]},
    "100": {"input_types": ["int"], "output_types": ["matplotlib.axes.Axes", "str", "str", "str"]},
    "101": {"input_types": ["list"], "output_types": ["matplotlib.axes.Axes"]},
    "102": {"input_types": ["None"], "output_types": ["matplotlib.figure.Figure", "pd.DataFrame"]},
    "103": {"input_types": ["pandas.DataFrame"], "output_types": ["matplotlib.axes.Axes"]},
    "104": {"input_types": ["DataFrame", "list"], "output_types": ["matplotlib.axes.Axes"]},
    "105": {
        "input_types": ["pandas.DataFrame"],
        "output_types": ["matplotlib.figure.Figure", "seaborn.axisgrid.PairGrid"],
    },
    "106": {"input_types": ["DataFrame"], "output_types": ["tuple"]},
    "107": {"input_types": ["pandas.DataFrame", "int", "int"], "output_types": ["matplotlib.axes.Axes"]},
    "108": {"input_types": ["DataFrame", "str", "str"], "output_types": ["tuple"]},
    "109": {"input_types": ["pandas.DataFrame", "list", "list"], "output_types": ["matplotlib.axes.Axes"]},
    "110": {"input_types": ["DataFrame"], "output_types": ["Axes"]},
    "111": {"input_types": ["DataFrame"], "output_types": ["Axes"]},
    "112": {"input_types": ["DataFrame"], "output_types": ["Axes"]},
    "113": {"input_types": ["dict", "list"], "output_types": ["tuple"]},
    "114": {"input_types": ["dict"], "output_types": ["dict"]},
    "115": {"input_types": ["list"], "output_types": ["dict"]},
    "116": {"input_types": ["float", "float", "int"], "output_types": ["ndarray"]},
    "117": {"input_types": ["int", "int", "list", "list", "tuple", "tuple"], "output_types": ["pandas.DataFrame"]},
    "118": {"input_types": ["str", "str"], "output_types": ["list"]},
    "119": {"input_types": ["None"], "output_types": ["None"]},
    "120": {"input_types": ["datetime.datetime", "datetime.datetime", "int"], "output_types": ["pandas.Series"]},
    "121": {"input_types": ["list", "int"], "output_types": ["tuple"]},
    "122": {"input_types": ["list"], "output_types": ["numpy.ndarray"]},
    "123": {"input_types": ["list", "str", "str"], "output_types": ["DataFrame"]},
    "124": {"input_types": ["list", "int", "int"], "output_types": ["tuple"]},
    "125": {"input_types": ["list", "int"], "output_types": ["str"]},
    "126": {"input_types": ["list", "int"], "output_types": ["DataFrame"]},
    "127": {"input_types": ["str", "str", "str"], "output_types": ["int"]},
    "128": {"input_types": ["int"], "output_types": ["matplotlib.figure.Figure"]},
    "129": {"input_types": ["str"], "output_types": ["pd.DataFrame"]},
    "130": {"input_types": ["str", "int"], "output_types": ["tuple"]},
    "131": {"input_types": ["str", "int"], "output_types": ["tuple"]},
    "132": {"input_types": ["str"], "output_types": ["tuple"]},
    "133": {"input_types": ["DataFrame", "int"], "output_types": ["DataFrame", "Axes"]},
    "134": {"input_types": ["DataFrame", "int"], "output_types": ["Axes"]},
    "135": {"input_types": ["DataFrame"], "output_types": ["DataFrame", "Axes"]},
    "136": {"input_types": ["DataFrame"], "output_types": ["DataFrame", "Axes"]},
    "137": {"input_types": ["DataFrame"], "output_types": ["float"]},
    "138": {"input_types": ["DataFrame", "list"], "output_types": ["Axes"]},
    "139": {"input_types": ["DataFrame"], "output_types": ["list"]},
    "140": {"input_types": ["DataFrame", "list"], "output_types": ["DataFrame"]},
    "141": {"input_types": ["int", "list", "int"], "output_types": ["DataFrame", "dict"]},
    "142": {"input_types": ["None"], "output_types": ["Figure", "ndarray"]},
    "143": {"input_types": ["None"], "output_types": ["matplotlib.axes.Axes"]},
    "144": {"input_types": ["str", "int"], "output_types": ["list"]},
    "145": {"input_types": ["str", "str"], "output_types": ["str"]},
    "146": {"input_types": ["str"], "output_types": ["dict"]},
    "147": {"input_types": ["str", "int"], "output_types": ["dict"]},
    "148": {"input_types": ["pd.DataFrame", "str"], "output_types": ["pd.DataFrame"]},
    "149": {"input_types": ["list", "bool"], "output_types": ["DataFrame"]},
    "150": {"input_types": ["dict", "list"], "output_types": ["tuple", "DataFrame", "Axes", "None"]},
    "151": {"input_types": ["dict", "list"], "output_types": ["tuple"]},
    "152": {"input_types": ["None"], "output_types": ["DataFrame"]},
    "153": {"input_types": ["list"], "output_types": ["DataFrame"]},
    "154": {"input_types": ["str", "str", "str"], "output_types": ["dict"]},
    "155": {"input_types": ["numpy.array"], "output_types": ["tuple", "DataFrame", "Axes"]},
    "156": {"input_types": ["numpy.array"], "output_types": ["DataFrame", "Axes"]},
    "157": {"input_types": ["numpy.array"], "output_types": ["tuple", "DataFrame", "Axes"]},
    "158": {"input_types": ["str", "str"], "output_types": ["str"]},
    "159": {"input_types": ["numpy.array"], "output_types": ["bytes"]},
    "160": {"input_types": ["numpy.array"], "output_types": ["tuple", "DataFrame", "Axes", "float"]},
    "161": {"input_types": ["str"], "output_types": ["str"]},
    "162": {"input_types": ["str", "float"], "output_types": ["matplotlib.axes.Axes"]},
    "163": {"input_types": ["int", "int"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "164": {"input_types": ["int", "tuple"], "output_types": ["matplotlib.figure.Figure"]},
    "165": {"input_types": ["int", "tuple"], "output_types": ["matplotlib.figure.Figure"]},
    "166": {"input_types": ["datetime", "datetime", "str"], "output_types": ["list"]},
    "167": {"input_types": ["int", "tuple"], "output_types": ["tuple"]},
    "168": {
        "input_types": ["int", "int", "list"],
        "output_types": ["tuple", "matplotlib.figure.Figure", "pandas.DataFrame", "str"],
    },
    "169": {"input_types": ["numpy.ndarray", "float"], "output_types": ["matplotlib.axes.Axes", "numpy.ndarray"]},
    "170": {"input_types": ["str", "str"], "output_types": ["DataFrame"]},
    "171": {"input_types": ["dict", "int"], "output_types": ["DataFrame"]},
    "172": {"input_types": ["str"], "output_types": ["bool"]},
    "173": {"input_types": ["dict"], "output_types": ["DataFrame"]},
    "174": {"input_types": ["DataFrame", "str", "int", "int"], "output_types": ["DataFrame"]},
    "175": {"input_types": ["DataFrame"], "output_types": ["Axes"]},
    "176": {"input_types": ["list"], "output_types": ["dict"]},
    "177": {"input_types": ["DataFrame"], "output_types": ["dict"]},
    "178": {"input_types": ["str"], "output_types": ["str"]},
    "179": {"input_types": ["DataFrame"], "output_types": ["Axes"]},
    "180": {"input_types": ["str", "list"], "output_types": ["list"]},
    "181": {"input_types": ["str", "int", "int"], "output_types": ["HttpResponse"]},
    "182": {"input_types": ["pd.DataFrame"], "output_types": ["list"]},
    "183": {"input_types": ["str"], "output_types": ["HttpResponse"]},
    "184": {"input_types": ["DataFrame", "str"], "output_types": ["DataFrame"]},
    "185": {"input_types": ["dict", "list"], "output_types": ["tuple"]},
    "186": {"input_types": ["dict"], "output_types": ["tuple"]},
    "187": {"input_types": ["dict", "list"], "output_types": ["GeoDataFrame"]},
    "188": {"input_types": ["dict"], "output_types": ["folium.Map"]},
    "189": {"input_types": ["str"], "output_types": ["list"]},
    "190": {"input_types": ["str", "StringIO"], "output_types": ["DataFrame"]},
    "191": {"input_types": ["list"], "output_types": ["dict"]},
    "192": {"input_types": ["str", "str", "int", "str", "str", "str"], "output_types": ["list"]},
    "193": {"input_types": ["int", "int"], "output_types": ["pd.DataFrame"]},
    "194": {"input_types": ["int"], "output_types": ["tuple", "ndarray", "str"]},
    "195": {"input_types": ["str"], "output_types": ["int"]},
    "196": {"input_types": ["int", "int", "int"], "output_types": ["Tuple", "List"]},
    "197": {"input_types": ["list", "list", "int"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "198": {"input_types": ["list", "float"], "output_types": ["numpy.ndarray", "int"]},
    "199": {"input_types": ["datetime", "list", "list", "dict", "int"], "output_types": ["pandas.DataFrame"]},
    "200": {"input_types": ["int", "float"], "output_types": ["list", "int"]},
    "201": {"input_types": ["DataFrame", "str", "float"], "output_types": ["tuple"]},
    "202": {"input_types": ["str", "int"], "output_types": ["dict"]},
    "203": {"input_types": ["str", "str", "int", "str", "str"], "output_types": ["list"]},
    "204": {"input_types": ["list"], "output_types": ["dict"]},
    "205": {"input_types": ["list"], "output_types": ["list"]},
    "206": {"input_types": ["str"], "output_types": ["str"]},
    "207": {"input_types": ["str"], "output_types": ["dict"]},
    "208": {"input_types": ["int", "int"], "output_types": ["dict", "matplotlib.axes.Axes"]},
    "209": {"input_types": ["list"], "output_types": ["matplotlib.axes.Axes"]},
    "210": {"input_types": ["list"], "output_types": ["matplotlib.axes.Axes"]},
    "211": {"input_types": ["str", "str", "dict"], "output_types": ["list"]},
    "212": {"input_types": ["list"], "output_types": ["matplotlib.axes.Axes", "tuple"]},
    "213": {"input_types": ["int"], "output_types": ["matplotlib.axes.Axes", "float"]},
    "214": {"input_types": ["int", "tuple", "int", "int"], "output_types": ["matplotlib.axes.Axes", "numpy.ndarray"]},
    "215": {"input_types": ["str", "dict"], "output_types": ["tuple", "DataFrame", "Axes"]},
    "216": {"input_types": ["str", "int"], "output_types": ["list"]},
    "217": {"input_types": ["float", "float", "int"], "output_types": ["matplotlib.axes._axes.Axes", "float", "float"]},
    "218": {"input_types": ["DataFrame", "dict", "bool"], "output_types": ["DataFrame", "Axes", "None"]},
    "219": {"input_types": ["list"], "output_types": ["tuple"]},
    "220": {"input_types": ["list"], "output_types": ["None"]},
    "221": {"input_types": ["DataFrame", "dict"], "output_types": ["dict"]},
    "222": {"input_types": ["list"], "output_types": ["tuple", "numpy array", "matplotlib.axes._axes.Axes"]},
    "223": {"input_types": ["DataFrame", "dict", "list"], "output_types": ["DataFrame"]},
    "224": {"input_types": ["None"], "output_types": ["tuple", "generator", "Axes", "float", "float"]},
    "225": {"input_types": ["DataFrame", "dict", "list", "bool"], "output_types": ["DataFrame"]},
    "226": {"input_types": ["None"], "output_types": ["generator", "Axes"]},
    "227": {
        "input_types": ["list", "int", "int", "str"],
        "output_types": ["numpy.ndarray", "matplotlib.figure.Figure"],
    },
    "228": {"input_types": ["DataFrame", "dict"], "output_types": ["DataFrame"]},
    "229": {"input_types": ["str", "int", "int"], "output_types": ["str"]},
    "230": {"input_types": ["DataFrame"], "output_types": ["Figure"]},
    "231": {"input_types": ["list", "str"], "output_types": ["Axes"]},
    "232": {"input_types": ["DataFrame"], "output_types": ["dict"]},
    "233": {"input_types": ["list", "str", "int", "int"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "234": {"input_types": ["DataFrame"], "output_types": ["tuple"]},
    "235": {"input_types": ["float", "float", "int", "int", "int"], "output_types": ["matplotlib.axes.Axes"]},
    "236": {"input_types": ["DataFrame", "float", "int"], "output_types": ["float"]},
    "237": {"input_types": ["list", "bool", "str"], "output_types": ["numpy.ndarray", "matplotlib.axes._axes.Axes"]},
    "238": {"input_types": ["pandas.DataFrame"], "output_types": ["pandas.DataFrame", "matplotlib.axes.Axes"]},
    "239": {"input_types": ["list"], "output_types": ["np.array", "dict", "Axes"]},
    "240": {"input_types": ["int", "float", "float", "str"], "output_types": ["DataFrame"]},
    "241": {"input_types": ["list"], "output_types": ["np.array", "np.array", "matplotlib.axes.Axes"]},
    "242": {"input_types": ["str", "int"], "output_types": ["tuple"]},
    "243": {"input_types": ["int"], "output_types": ["DataFrame"]},
    "244": {"input_types": ["list"], "output_types": ["np.array", "np.array", "plt.Axes"]},
    "245": {"input_types": ["int", "float", "float"], "output_types": ["dict"]},
    "246": {"input_types": ["int", "int"], "output_types": ["list", "np.array", "plt.Axes"]},
    "247": {"input_types": ["int", "float", "float"], "output_types": ["DataFrame"]},
    "248": {"input_types": ["list"], "output_types": ["Axes"]},
    "249": {"input_types": ["int", "float", "float", "float"], "output_types": ["tuple"]},
    "250": {"input_types": ["list", "str"], "output_types": ["dict"]},
    "251": {"input_types": ["DataFrame"], "output_types": ["Figure"]},
    "252": {"input_types": ["list", "list"], "output_types": ["matplotlib.axes.Axes"]},
    "253": {"input_types": ["matplotlib.axes._axes.Axes"], "output_types": ["str"]},
    "254": {"input_types": ["datetime", "int"], "output_types": ["str"]},
    "255": {"input_types": ["matplotlib.axes._axes.Axes", "int"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "256": {"input_types": ["datetime", "str", "int", "int"], "output_types": ["str"]},
    "257": {"input_types": ["matplotlib.axes._axes.Axes", "int"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "258": {"input_types": ["datetime", "int"], "output_types": ["str"]},
    "259": {"input_types": ["matplotlib.axes._axes.Axes", "int"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "260": {"input_types": ["str"], "output_types": ["int"]},
    "261": {"input_types": ["matplotlib.axes._axes.Axes", "float"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "262": {"input_types": ["dict", "str", "str"], "output_types": ["dict", "matplotlib.axes.Axes"]},
    "263": {"input_types": ["str", "int"], "output_types": ["str"]},
    "264": {"input_types": ["dict", "str", "str", "int", "int", "int"], "output_types": ["tuple"]},
    "265": {"input_types": ["dict", "str"], "output_types": ["str"]},
    "266": {"input_types": ["str"], "output_types": ["str"]},
    "267": {"input_types": ["dict"], "output_types": ["tuple", "ndarray", "Axes"]},
    "268": {"input_types": ["int", "int"], "output_types": ["dict"]},
    "269": {"input_types": ["dict"], "output_types": ["tuple", "dict", "dict", "matplotlib.axes.Axes"]},
    "270": {"input_types": ["str"], "output_types": ["dict"]},
    "271": {"input_types": ["dict", "int"], "output_types": ["dict"]},
    "272": {"input_types": ["None"], "output_types": ["class"]},
    "273": {"input_types": ["None"], "output_types": ["list"]},
    "274": {"input_types": ["str", "int", "str", "str"], "output_types": ["class"]},
    "275": {"input_types": ["int"], "output_types": ["list"]},
    "276": {"input_types": ["list"], "output_types": ["tuple"]},
    "277": {"input_types": ["int"], "output_types": ["tuple", "None"]},
    "278": {"input_types": ["int", "int"], "output_types": ["tuple"]},
    "279": {"input_types": ["int"], "output_types": ["tuple", "list", "Counter"]},
    "280": {"input_types": ["array", "int", "int"], "output_types": ["ndarray", "tuple"]},
    "281": {"input_types": ["str"], "output_types": ["dict"]},
    "282": {"input_types": ["str", "function"], "output_types": ["matplotlib.axes.Axes"]},
    "283": {"input_types": ["str", "str"], "output_types": ["dict"]},
    "284": {"input_types": ["str"], "output_types": ["list"]},
    "285": {"input_types": ["str", "int", "dict"], "output_types": ["str"]},
    "286": {"input_types": ["str", "str"], "output_types": ["int"]},
    "287": {"input_types": ["str", "str"], "output_types": ["int"]},
    "288": {"input_types": ["str"], "output_types": ["dict"]},
    "289": {"input_types": ["numpy.array", "numpy.array", "int", "int", "int"], "output_types": ["list"]},
    "290": {"input_types": ["str"], "output_types": ["int"]},
    "291": {"input_types": ["float", "float", "int"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "292": {"input_types": ["DataFrame"], "output_types": ["tuple"]},
    "293": {"input_types": ["tuple", "int"], "output_types": ["matplotlib.axes.Axes", "list", "list"]},
    "294": {"input_types": ["DataFrame"], "output_types": ["DataFrame"]},
    "295": {"input_types": ["tuple", "int"], "output_types": ["dict"]},
    "296": {"input_types": ["DataFrame"], "output_types": ["Axes"]},
    "297": {"input_types": ["None"], "output_types": ["dict"]},
    "298": {"input_types": ["DataFrame", "bool"], "output_types": ["DataFrame", "Axes"]},
    "299": {"input_types": ["tuple", "int", "int"], "output_types": ["int", "list"]},
    "300": {"input_types": ["DataFrame"], "output_types": ["DataFrame", "Figure"]},
    "301": {"input_types": ["str", "str", "str"], "output_types": ["float"]},
    "302": {"input_types": ["DataFrame", "bool"], "output_types": ["DataFrame", "Axes"]},
    "303": {"input_types": ["str", "str", "str"], "output_types": ["float"]},
    "304": {"input_types": ["DataFrame"], "output_types": ["tuple", "ndarray", "Axes"]},
    "305": {"input_types": ["list", "int"], "output_types": ["Counter"]},
    "306": {"input_types": ["str"], "output_types": ["tuple"]},
    "307": {"input_types": ["list", "int"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "308": {"input_types": ["list"], "output_types": ["DataFrame"]},
    "309": {"input_types": ["list", "int"], "output_types": ["list"]},
    "310": {"input_types": ["str"], "output_types": ["str"]},
    "311": {"input_types": ["list", "int", "int"], "output_types": ["dict"]},
    "312": {"input_types": ["int"], "output_types": ["tuple"]},
    "313": {"input_types": ["str"], "output_types": ["tuple", "str", "dict"]},
    "314": {"input_types": ["str", "int", "str"], "output_types": ["str"]},
    "315": {"input_types": ["str", "str", "str"], "output_types": ["bool"]},
    "316": {"input_types": ["tuple"], "output_types": ["DataFrame"]},
    "317": {"input_types": ["str"], "output_types": ["dict"]},
    "318": {"input_types": ["int", "float"], "output_types": ["Axes"]},
    "319": {"input_types": ["str", "int"], "output_types": ["Axes", "dict"]},
    "320": {"input_types": ["str", "list"], "output_types": ["int"]},
    "321": {"input_types": ["str"], "output_types": ["tuple", "pd.Series", "Axes", "float", "float"]},
    "322": {"input_types": ["str"], "output_types": ["int"]},
    "323": {"input_types": ["str", "int", "int"], "output_types": ["dict"]},
    "324": {"input_types": ["list"], "output_types": ["list"]},
    "325": {"input_types": ["str", "str"], "output_types": ["dict"]},
    "326": {"input_types": ["str"], "output_types": ["list"]},
    "327": {"input_types": ["str", "str"], "output_types": ["dict"]},
    "328": {"input_types": ["int"], "output_types": ["OrderedDict"]},
    "329": {"input_types": ["str"], "output_types": ["dict"]},
    "330": {"input_types": ["int", "int"], "output_types": ["tuple", "list", "list"]},
    "331": {"input_types": ["int", "int", "int", "int"], "output_types": ["tuple", "list", "list"]},
    "332": {"input_types": ["str"], "output_types": ["dict"]},
    "333": {"input_types": ["int", "int", "int", "int"], "output_types": ["tuple"]},
    "334": {"input_types": ["list"], "output_types": ["pandas.DataFrame"]},
    "335": {"input_types": ["int"], "output_types": ["collections.OrderedDict"]},
    "336": {"input_types": ["str", "str", "list"], "output_types": ["list"]},
    "337": {"input_types": ["DataFrame", "str", "str"], "output_types": ["Axes"]},
    "338": {"input_types": ["list", "int"], "output_types": ["list", "plt.Axes", "dict"]},
    "339": {"input_types": ["dict", "str"], "output_types": ["str"]},
    "340": {"input_types": ["dict"], "output_types": ["tuple", "str", "str"]},
    "341": {"input_types": ["DataFrame", "str"], "output_types": ["Figure"]},
    "342": {"input_types": ["list", "str", "int"], "output_types": ["list", "bool"]},
    "343": {"input_types": ["DataFrame", "str", "str"], "output_types": ["Axes"]},
    "344": {"input_types": ["str", "str"], "output_types": ["bool"]},
    "345": {"input_types": ["DataFrame", "str", "str"], "output_types": ["Axes"]},
    "346": {"input_types": ["str", "bool", "list"], "output_types": ["int", "None"]},
    "347": {"input_types": ["DataFrame", "str"], "output_types": ["Series"]},
    "348": {"input_types": ["str"], "output_types": ["int"]},
    "349": {"input_types": ["list", "list"], "output_types": ["DataFrame"]},
    "350": {"input_types": ["str", "str"], "output_types": ["dict"]},
    "351": {"input_types": ["list", "list", "int", "int"], "output_types": ["DataFrame"]},
    "352": {"input_types": ["dict", "list", "int"], "output_types": ["matplotlib.axes._axes.Axes", "dict"]},
    "353": {"input_types": ["list", "list", "int", "int"], "output_types": ["DataFrame"]},
    "354": {"input_types": ["dict", "list"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "355": {
        "input_types": ["float", "float", "numpy.ndarray"],
        "output_types": ["numpy.ndarray", "matplotlib.figure.Figure", "matplotlib.axes.Axes"],
    },
    "356": {
        "input_types": ["numpy.ndarray", "numpy.ndarray"],
        "output_types": ["tuple", "matplotlib.axes.Axes", "numpy.ndarray"],
    },
    "357": {"input_types": ["numpy.ndarray"], "output_types": ["numpy.ndarray"]},
    "358": {"input_types": ["str", "int"], "output_types": ["list"]},
    "359": {"input_types": ["dict", "list"], "output_types": ["tuple", "float", "Axes"]},
    "360": {"input_types": ["str", "str"], "output_types": ["dict", "matplotlib.figure.Figure"]},
    "361": {"input_types": ["str", "str", "str"], "output_types": ["dict"]},
    "362": {"input_types": ["str", "str", "str"], "output_types": ["DataFrame"]},
    "363": {"input_types": ["list"], "output_types": ["dict"]},
    "364": {"input_types": ["DataFrame"], "output_types": ["LinearRegression"]},
    "365": {"input_types": ["int", "str", "int"], "output_types": ["str"]},
    "366": {"input_types": ["list", "int"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "367": {"input_types": ["list"], "output_types": ["matplotlib.axes.Axes"]},
    "368": {"input_types": ["str", "str", "int"], "output_types": ["str"]},
    "369": {"input_types": ["numpy array"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "370": {"input_types": ["str"], "output_types": ["list"]},
    "371": {"input_types": ["numpy array"], "output_types": ["DataFrame"]},
    "372": {"input_types": ["str"], "output_types": ["int"]},
    "373": {"input_types": ["numpy array", "numpy array", "bool"], "output_types": ["tuple"]},
    "374": {"input_types": ["str"], "output_types": ["int"]},
    "375": {"input_types": ["numpy array"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "376": {"input_types": ["str"], "output_types": ["dict"]},
    "377": {"input_types": ["None"], "output_types": ["list"]},
    "378": {"input_types": ["str"], "output_types": ["str"]},
    "379": {"input_types": ["int"], "output_types": ["DataFrame"]},
    "380": {"input_types": ["str"], "output_types": ["None"]},
    "381": {"input_types": ["str", "str", "int"], "output_types": ["matplotlib.axes.Axes", "numpy.ndarray"]},
    "382": {"input_types": ["int"], "output_types": ["tuple"]},
    "383": {"input_types": ["str", "int", "int"], "output_types": ["None"]},
    "384": {"input_types": ["dict", "int", "int"], "output_types": ["tuple"]},
    "385": {"input_types": ["dict"], "output_types": ["dict", "matplotlib.axes.Axes"]},
    "386": {"input_types": ["int", "int", "int"], "output_types": ["DataFrame"]},
    "387": {"input_types": ["dict", "int", "int"], "output_types": ["dict", "matplotlib.axes.Axes"]},
    "388": {"input_types": ["tuple", "list"], "output_types": ["dict"]},
    "389": {"input_types": ["str"], "output_types": ["list"]},
    "390": {"input_types": ["dict", "str"], "output_types": ["DataFrame"]},
    "391": {"input_types": ["str", "str"], "output_types": ["tuple"]},
    "392": {"input_types": ["DataFrame", "str", "str", "str"], "output_types": ["Axes"]},
    "393": {"input_types": ["float", "float", "int", "int"], "output_types": ["matplotlib.figure.Figure"]},
    "394": {"input_types": ["int", "int"], "output_types": ["dict"]},
    "395": {"input_types": ["str", "str", "str"], "output_types": ["DataFrame"]},
    "396": {"input_types": ["float", "float", "int", "int"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "397": {"input_types": ["str"], "output_types": ["str"]},
    "398": {"input_types": ["str"], "output_types": ["bool"]},
    "399": {"input_types": ["float", "int"], "output_types": ["matplotlib.figure.Figure", "matplotlib.axes.Axes"]},
    "400": {"input_types": ["str", "str"], "output_types": ["list"]},
    "401": {"input_types": ["string"], "output_types": ["tuple"]},
    "402": {"input_types": ["str"], "output_types": ["str"]},
    "403": {"input_types": ["str", "int"], "output_types": ["tuple"]},
    "404": {"input_types": ["str"], "output_types": ["tuple"]},
    "405": {"input_types": ["int"], "output_types": ["tuple"]},
    "406": {"input_types": ["str", "float"], "output_types": ["tuple"]},
    "407": {"input_types": ["str", "str", "str"], "output_types": ["str"]},
    "408": {"input_types": ["str", "str"], "output_types": ["pd.DataFrame"]},
    "409": {"input_types": ["str", "str", "str"], "output_types": ["dict"]},
    "410": {"input_types": ["str", "str", "str", "str", "str"], "output_types": ["pd.DataFrame"]},
    "411": {"input_types": ["dict", "str"], "output_types": ["str"]},
    "412": {"input_types": ["str"], "output_types": ["dict"]},
    "413": {"input_types": ["Flask"], "output_types": ["tuple"]},
    "414": {"input_types": ["dict", "str"], "output_types": ["pd.DataFrame", "matplotlib.axes._axes.Axes", "None"]},
    "415": {"input_types": ["pd.DataFrame"], "output_types": ["pd.DataFrame"]},
    "416": {"input_types": ["dict", "str"], "output_types": ["matplotlib.axes._axes.Axes", "None"]},
    "417": {"input_types": ["np.ndarray", "np.ndarray"], "output_types": ["Sequential", "matplotlib.axes.Axes"]},
    "418": {
        "input_types": ["np.ndarray", "np.ndarray"],
        "output_types": ["keras.models.Sequential", "matplotlib.axes._axes.Axes"],
    },
    "419": {
        "input_types": ["np.ndarray", "np.ndarray"],
        "output_types": ["keras.models.Sequential", "matplotlib.axes._axes.Axes"],
    },
    "420": {"input_types": ["dict"], "output_types": ["pd.DataFrame"]},
    "421": {"input_types": ["str", "str", "dict"], "output_types": ["list"]},
    "422": {
        "input_types": ["dict", "str", "str", "float"],
        "output_types": ["pd.DataFrame", "pd.DataFrame", "pd.Series", "pd.Series"],
    },
    "423": {"input_types": ["str", "int"], "output_types": ["tuple"]},
    "424": {"input_types": ["str", "int", "int"], "output_types": ["tuple"]},
    "425": {"input_types": ["str", "str"], "output_types": ["matplotlib.axes.Axes"]},
    "426": {"input_types": ["str", "int"], "output_types": ["tuple"]},
    "427": {"input_types": ["DataFrame", "DataFrame", "list", "str"], "output_types": ["dict"]},
    "428": {
        "input_types": ["pd.DataFrame", "pd.DataFrame"],
        "output_types": ["pd.DataFrame", "seaborn.axisgrid.PairGrid"],
    },
    "429": {"input_types": ["pd.DataFrame", "pd.DataFrame"], "output_types": ["tuple", "list", "Axes"]},
    "430": {
        "input_types": ["pd.DataFrame", "pd.DataFrame", "str", "str"],
        "output_types": ["numpy.ndarray", "matplotlib.axes._axes.Axes"],
    },
    "431": {"input_types": ["str"], "output_types": ["np.ndarray"]},
    "432": {"input_types": ["DataFrame", "DataFrame", "str", "str"], "output_types": ["tuple"]},
    "433": {"input_types": ["str", "str", "str"], "output_types": ["bool"]},
    "434": {"input_types": ["str", "int"], "output_types": ["pd.DataFrame"]},
    "435": {"input_types": ["str", "int", "str", "float", "str"], "output_types": ["pd.DataFrame"]},
    "436": {"input_types": ["str"], "output_types": ["tuple", "dict", "Axes"]},
    "437": {"input_types": ["DataFrame", "str"], "output_types": ["DataFrame"]},
    "438": {"input_types": ["list", "str"], "output_types": ["matplotlib.figure.Figure"]},
    "439": {
        "input_types": ["numpy.ndarray", "numpy.ndarray"],
        "output_types": ["numpy.ndarray", "matplotlib.axes.Axes"],
    },
    "440": {"input_types": ["numpy.ndarray", "numpy.ndarray"], "output_types": ["pandas.DataFrame"]},
    "441": {
        "input_types": ["numpy.ndarray", "numpy.ndarray"],
        "output_types": ["tuple", "numpy.ndarray", "mpl_toolkits.mplot3d.axes3d.Axes3D"],
    },
    "442": {
        "input_types": ["numpy.ndarray", "numpy.ndarray", "tuple"],
        "output_types": ["numpy.ndarray", "matplotlib.axes.Axes"],
    },
    "443": {
        "input_types": ["numpy.ndarray", "numpy.ndarray", "int", "int", "int"],
        "output_types": ["numpy.ndarray", "matplotlib.axes.Axes"],
    },
    "444": {"input_types": ["int", "int"], "output_types": ["tuple"]},
    "445": {"input_types": ["ndarray", "int"], "output_types": ["tuple", "Voronoi", "Axes"]},
    "446": {
        "input_types": ["int", "int", "int", "int"],
        "output_types": ["tuple", "numpy.ndarray", "numpy.ndarray", "matplotlib.axes.Axes"],
    },
    "447": {"input_types": ["ndarray", "int", "int"], "output_types": ["dict"]},
    "448": {"input_types": ["float", "float"], "output_types": ["matplotlib.axes.Axes"]},
    "449": {"input_types": ["pd.DataFrame"], "output_types": ["pd.DataFrame", "list"]},
    "450": {"input_types": ["int", "int", "str", "int"], "output_types": ["tuple", "ndarray", "Axes", "None"]},
    "451": {"input_types": ["int", "int", "int", "int"], "output_types": ["tuple"]},
    "452": {"input_types": ["int", "int", "int"], "output_types": ["tuple"]},
    "453": {"input_types": ["int", "str"], "output_types": ["str"]},
    "454": {"input_types": ["str", "str", "str"], "output_types": ["list"]},
    "455": {"input_types": ["float", "float", "int"], "output_types": ["numpy.ndarray"]},
    "456": {"input_types": ["pd.DataFrame"], "output_types": ["pd.DataFrame", "plt.Axes"]},
    "457": {"input_types": ["list"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "458": {"input_types": ["str"], "output_types": ["DataFrame"]},
    "459": {"input_types": ["str", "list", "int"], "output_types": ["list"]},
    "460": {"input_types": ["str", "str"], "output_types": ["pd.DataFrame", "matplotlib.axes._axes.Axes"]},
    "461": {"input_types": ["str", "int"], "output_types": ["dict"]},
    "462": {"input_types": ["int", "list", "int"], "output_types": ["pd.DataFrame", "matplotlib.pyplot.Axes"]},
    "463": {"input_types": ["str", "str", "int"], "output_types": ["tuple"]},
    "464": {"input_types": ["object"], "output_types": ["str"]},
    "465": {"input_types": ["object"], "output_types": ["str"]},
    "466": {"input_types": ["object"], "output_types": ["str"]},
    "467": {"input_types": ["int", "int"], "output_types": ["matplotlib.figure.Figure", "list"]},
    "468": {"input_types": ["str", "list"], "output_types": ["tuple", "DataFrame", "Axes", "Series"]},
    "469": {"input_types": ["list", "list"], "output_types": ["Tuple", "Axes"]},
    "470": {"input_types": ["list"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "471": {"input_types": ["list"], "output_types": ["DataFrame"]},
    "472": {"input_types": ["list", "int"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "473": {"input_types": ["int", "int", "int"], "output_types": ["plt.Axes"]},
    "474": {
        "input_types": ["int", "float", "float", "int"],
        "output_types": ["matplotlib.axes._axes.Axes", "numpy.ndarray"],
    },
    "475": {"input_types": ["DataFrame", "str", "str", "dict"], "output_types": ["Axes"]},
    "476": {"input_types": ["list", "numpy.array"], "output_types": ["tuple", "list", "matplotlib.axes.Axes"]},
    "477": {"input_types": ["int", "list", "int"], "output_types": ["tuple", "DataFrame", "Axes"]},
    "478": {"input_types": ["list", "int"], "output_types": ["DataFrame"]},
    "479": {"input_types": ["list", "int"], "output_types": ["DataFrame"]},
    "480": {"input_types": ["list", "int"], "output_types": ["DataFrame"]},
    "481": {"input_types": ["list", "int"], "output_types": ["pandas.DataFrame"]},
    "482": {"input_types": ["list", "int"], "output_types": ["pd.DataFrame"]},
    "483": {"input_types": ["pd.DataFrame", "str", "str"], "output_types": ["pd.DataFrame"]},
    "484": {"input_types": ["int", "int", "int", "list", "list", "int"], "output_types": ["pd.DataFrame"]},
    "485": {"input_types": ["str", "str"], "output_types": ["matplotlib.axes.Axes"]},
    "486": {"input_types": ["int", "int", "int", "float", "int"], "output_types": ["matplotlib.pyplot.Axes"]},
    "487": {"input_types": ["str"], "output_types": ["pd.DataFrame"]},
    "488": {"input_types": ["int", "int", "int", "float", "int", "int"], "output_types": ["matplotlib.pyplot.Axes"]},
    "489": {"input_types": ["int", "int"], "output_types": ["pd.DataFrame"]},
    "490": {"input_types": ["str", "str"], "output_types": ["dict"]},
    "491": {"input_types": ["int", "int"], "output_types": ["dict", "plt.Axes"]},
    "492": {"input_types": ["int", "int", "list"], "output_types": ["pd.DataFrame"]},
    "493": {"input_types": ["int", "list", "int"], "output_types": ["dict", "matplotlib.figure.Figure"]},
    "494": {"input_types": ["int", "int", "list"], "output_types": ["dict"]},
    "495": {"input_types": ["int", "int"], "output_types": ["pd.DataFrame"]},
    "496": {"input_types": ["int", "int"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "497": {"input_types": ["int"], "output_types": ["str"]},
    "498": {"input_types": ["str", "bool", "str"], "output_types": ["dict"]},
    "499": {"input_types": ["str", "str"], "output_types": ["str"]},
    "500": {"input_types": ["list", "str"], "output_types": ["str"]},
    "501": {"input_types": ["str", "str", "str"], "output_types": ["str"]},
    "502": {"input_types": ["int", "int"], "output_types": ["tuple", "matplotlib.pyplot.Axes", "pd.DataFrame"]},
    "503": {"input_types": ["int", "list", "int"], "output_types": ["DataFrame"]},
    "504": {"input_types": ["str"], "output_types": ["str"]},
    "505": {"input_types": ["str", "str"], "output_types": ["str"]},
    "506": {"input_types": ["str", "list"], "output_types": ["dict"]},
    "507": {"input_types": ["str", "list"], "output_types": ["dict"]},
    "508": {"input_types": ["str", "str"], "output_types": ["bool"]},
    "509": {"input_types": ["str", "str", "str", "str"], "output_types": ["DataFrame"]},
    "510": {"input_types": ["str", "str"], "output_types": ["str"]},
    "511": {"input_types": ["str", "list"], "output_types": ["tuple", "dict", "Axes"]},
    "512": {"input_types": ["str", "list"], "output_types": ["tuple", "dict", "matplotlib.axes.Axes"]},
    "513": {"input_types": ["str", "list"], "output_types": ["tuple", "dict", "matplotlib.axes.Axes"]},
    "514": {"input_types": ["list"], "output_types": ["DataFrame", "Axes"]},
    "515": {"input_types": ["list"], "output_types": ["DataFrame", "heatmap"]},
    "516": {"input_types": ["list"], "output_types": ["pd.DataFrame", "statsmodels.RegressionResults"]},
    "517": {"input_types": ["list", "int"], "output_types": ["pd.DataFrame", "np.ndarray"]},
    "518": {"input_types": ["list"], "output_types": ["pd.DataFrame", "pd.DataFrame"]},
    "519": {"input_types": ["list"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "520": {"input_types": ["list"], "output_types": ["dict", "matplotlib.container.BarContainer"]},
    "521": {"input_types": ["list"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "522": {"input_types": ["list"], "output_types": ["matplotlib.axes._axes.Axes", "None"]},
    "523": {"input_types": ["list"], "output_types": ["matplotlib.axes._axes.Axes", "None"]},
    "524": {"input_types": ["list"], "output_types": ["tuple", "dict", "list"]},
    "525": {"input_types": ["str"], "output_types": ["dict", "list"]},
    "526": {"input_types": ["str"], "output_types": ["pd.DataFrame"]},
    "527": {"input_types": ["str"], "output_types": ["dict", "plt.Axes"]},
    "528": {"input_types": ["str"], "output_types": ["dict", "Axes"]},
    "529": {"input_types": ["int", "int", "str", "int"], "output_types": ["tuple", "Counter", "Axes"]},
    "530": {"input_types": ["pd.DataFrame"], "output_types": ["Counter", "plt.Axes", "None"]},
    "531": {
        "input_types": ["pd.DataFrame", "int", "int", "int"],
        "output_types": ["tuple", "Counter", "pd.DataFrame", "Axes"],
    },
    "532": {"input_types": ["pd.DataFrame", "int"], "output_types": ["tuple", "Counter", "matplotlib.axes.Axes"]},
    "533": {"input_types": ["str", "int", "int", "str"], "output_types": ["tuple"]},
    "534": {"input_types": ["str", "int", "int", "Any", "str"], "output_types": ["str"]},
    "535": {"input_types": ["str", "str", "int", "int"], "output_types": ["int"]},
    "536": {"input_types": ["str", "str", "str"], "output_types": ["str"]},
    "537": {"input_types": ["str", "str"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "538": {"input_types": ["str", "str"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "539": {"input_types": ["str", "str", "int", "int"], "output_types": ["str"]},
    "540": {"input_types": ["list", "str", "str", "float"], "output_types": ["object"]},
    "541": {"input_types": ["str"], "output_types": ["list"]},
    "542": {"input_types": ["list", "int"], "output_types": ["str"]},
    "543": {"input_types": ["None"], "output_types": ["str"]},
    "544": {"input_types": ["str"], "output_types": ["bytes"]},
    "545": {"input_types": ["list"], "output_types": ["bytes"]},
    "546": {"input_types": ["dict"], "output_types": ["PrettyTable"]},
    "547": {"input_types": ["str", "int"], "output_types": ["str"]},
    "548": {"input_types": ["int"], "output_types": ["str"]},
    "549": {"input_types": ["dict"], "output_types": ["str"]},
    "550": {"input_types": ["list"], "output_types": ["DataFrame"]},
    "551": {"input_types": ["list"], "output_types": ["matplotlib.axes.Axes", "None"]},
    "552": {"input_types": ["list", "list", "list"], "output_types": ["matplotlib.axes.Axes"]},
    "553": {"input_types": ["list", "list"], "output_types": ["matplotlib.axes.Axes"]},
    "554": {"input_types": ["int", "int", "list"], "output_types": ["str"]},
    "555": {"input_types": ["list", "list"], "output_types": ["tuple", "float", "matplotlib.axes.Axes"]},
    "556": {"input_types": ["str", "int", "int", "str"], "output_types": ["tuple"]},
    "557": {"input_types": ["list", "str"], "output_types": ["list"]},
    "558": {"input_types": ["list", "list", "list"], "output_types": ["pd.DataFrame", "matplotlib.axes.Axes"]},
    "559": {"input_types": ["list", "list"], "output_types": ["float", "pd.DataFrame", "matplotlib.axes.Axes"]},
    "560": {"input_types": ["str"], "output_types": ["Axes"]},
    "561": {"input_types": ["str", "str", "str"], "output_types": ["str"]},
    "562": {"input_types": ["str"], "output_types": ["str"]},
    "563": {"input_types": ["str", "str"], "output_types": ["str"]},
    "564": {"input_types": ["str"], "output_types": ["str", "dict"]},
    "565": {"input_types": ["str"], "output_types": ["str"]},
    "566": {"input_types": ["function"], "output_types": ["dict"]},
    "567": {"input_types": ["str"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "568": {"input_types": ["list"], "output_types": ["pandas.DataFrame"]},
    "569": {"input_types": ["function"], "output_types": ["dict"]},
    "570": {"input_types": ["function"], "output_types": ["str"]},
    "571": {"input_types": ["list", "str"], "output_types": ["None"]},
    "572": {"input_types": ["int"], "output_types": ["matplotlib.axes.Axes"]},
    "573": {"input_types": ["int"], "output_types": ["DataFrame", "Axes"]},
    "574": {"input_types": ["int", "float"], "output_types": ["Axes"]},
    "575": {"input_types": ["list", "int"], "output_types": ["DataFrame"]},
    "576": {"input_types": ["list", "int"], "output_types": ["pd.Series"]},
    "577": {"input_types": ["str"], "output_types": ["dict"]},
    "578": {"input_types": ["str"], "output_types": ["dict"]},
    "579": {"input_types": ["str"], "output_types": ["tuple"]},
    "580": {"input_types": ["None"], "output_types": ["pd.DataFrame"]},
    "581": {"input_types": ["int", "float"], "output_types": ["Axes"]},
    "582": {"input_types": ["int"], "output_types": ["matplotlib.figure.Figure"]},
    "583": {"input_types": ["None"], "output_types": ["list", "str", "bytes", "bytes"]},
    "584": {"input_types": ["str"], "output_types": ["rsa.PublicKey", "str", "bytes"]},
    "585": {"input_types": ["str"], "output_types": ["rsa.PublicKey", "str"]},
    "586": {"input_types": ["str"], "output_types": ["PublicKey", "str", "str"]},
    "587": {"input_types": ["str"], "output_types": ["rsa.PublicKey", "str", "str"]},
    "588": {"input_types": ["None"], "output_types": ["pd.DataFrame"]},
    "589": {"input_types": ["None"], "output_types": ["tuple"]},
    "590": {"input_types": ["str"], "output_types": ["pandas.DataFrame"]},
    "591": {"input_types": ["int", "str"], "output_types": ["tuple", "str", "Axes"]},
    "592": {"input_types": ["int", "str"], "output_types": ["int"]},
    "593": {"input_types": ["int", "str"], "output_types": ["tuple"]},
    "594": {"input_types": ["int", "str"], "output_types": ["str"]},
    "595": {"input_types": ["int", "int"], "output_types": ["tuple"]},
    "596": {"input_types": ["int"], "output_types": ["tuple"]},
    "597": {"input_types": ["dict", "str"], "output_types": ["pd.Series"]},
    "598": {"input_types": ["dict", "str"], "output_types": ["dict"]},
    "599": {"input_types": ["dict", "str"], "output_types": ["Axes"]},
    "600": {"input_types": ["dict", "str"], "output_types": ["dict"]},
    "601": {"input_types": ["pd.DataFrame", "str"], "output_types": ["Axes", "None"]},
    "602": {"input_types": ["str", "str"], "output_types": ["None"]},
    "603": {"input_types": ["np.ndarray", "np.ndarray"], "output_types": ["str"]},
    "604": {"input_types": ["str"], "output_types": ["None"]},
    "605": {"input_types": ["array"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "606": {"input_types": ["array"], "output_types": ["DataFrame"]},
    "607": {"input_types": ["pd.DataFrame", "list", "int"], "output_types": ["pd.DataFrame", "list"]},
    "608": {"input_types": ["DataFrame", "list", "int"], "output_types": ["tuple", "DataFrame", "list"]},
    "609": {"input_types": ["pd.DataFrame", "list", "int"], "output_types": ["pd.DataFrame", "list"]},
    "610": {"input_types": ["DataFrame", "list", "int"], "output_types": ["tuple", "DataFrame", "list"]},
    "611": {"input_types": ["pd.DataFrame", "list", "int"], "output_types": ["tuple", "list"]},
    "612": {"input_types": ["dict", "dict", "list", "list"], "output_types": ["pd.DataFrame"]},
    "613": {"input_types": ["dict", "dict"], "output_types": ["DataFrame"]},
    "614": {"input_types": ["dict", "dict"], "output_types": ["tuple", "DataFrame", "Axes"]},
    "615": {"input_types": ["int", "int", "int"], "output_types": ["pd.DataFrame"]},
    "616": {"input_types": ["int", "int", "list", "int", "int"], "output_types": ["DataFrame", "Axes"]},
    "617": {"input_types": ["int", "int", "int", "list"], "output_types": ["DataFrame"]},
    "618": {"input_types": ["int", "int"], "output_types": ["pd.DataFrame", "list"]},
    "619": {"input_types": ["int", "int", "int"], "output_types": ["tuple", "pd.DataFrame", "LinearRegression"]},
    "620": {"input_types": ["list"], "output_types": ["DataFrame"]},
    "621": {"input_types": ["list"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "622": {"input_types": ["list"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "623": {"input_types": ["list"], "output_types": ["matplotlib.axes.Axes"]},
    "624": {"input_types": ["list"], "output_types": ["tuple"]},
    "625": {"input_types": ["list"], "output_types": ["DataFrame"]},
    "626": {"input_types": ["str", "str"], "output_types": ["tuple"]},
    "627": {"input_types": ["list"], "output_types": ["DataFrame"]},
    "628": {"input_types": ["None"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "629": {"input_types": ["list", "str", "str"], "output_types": ["None"]},
    "630": {"input_types": ["DataFrame", "str", "str"], "output_types": ["str"]},
    "631": {"input_types": ["pandas.DataFrame", "str", "str"], "output_types": ["str"]},
    "632": {"input_types": ["pd.DataFrame", "str"], "output_types": ["str"]},
    "633": {"input_types": ["str"], "output_types": ["dict"]},
    "634": {"input_types": ["list", "int"], "output_types": ["scipy.stats.ModeResult"]},
    "635": {"input_types": ["str", "int"], "output_types": ["tuple", "pd.DataFrame", "matplotlib.axes.Axes"]},
    "636": {"input_types": ["int"], "output_types": ["tuple", "DataFrame", "Axes"]},
    "637": {"input_types": ["int"], "output_types": ["Tuple"]},
    "638": {"input_types": ["int", "int"], "output_types": ["DataFrame"]},
    "639": {"input_types": ["int", "int"], "output_types": ["DataFrame", "Axes"]},
    "640": {"input_types": ["None"], "output_types": ["pd.DataFrame"]},
    "641": {"input_types": ["str", "str", "str"], "output_types": ["pd.DataFrame"]},
    "642": {"input_types": ["str", "str"], "output_types": ["dict"]},
    "643": {"input_types": ["pd.DataFrame", "str"], "output_types": ["pd.DataFrame"]},
    "644": {"input_types": ["str", "str", "str"], "output_types": ["str"]},
    "645": {"input_types": ["str"], "output_types": ["DataFrame"]},
    "646": {"input_types": ["str", "str"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "647": {"input_types": ["str", "str", "str"], "output_types": ["int"]},
    "648": {"input_types": ["str"], "output_types": ["datetime"]},
    "649": {"input_types": ["list"], "output_types": ["Series"]},
    "650": {"input_types": ["str", "str"], "output_types": ["int"]},
    "651": {"input_types": ["dict", "str"], "output_types": ["tuple", "pandas.Series", "matplotlib.Axes"]},
    "652": {"input_types": ["str", "np.ndarray"], "output_types": ["tuple"]},
    "653": {
        "input_types": ["pd.DataFrame", "str"],
        "output_types": ["tuple", "pd.DataFrame", "matplotlib.axes._axes.Axes"],
    },
    "654": {"input_types": ["np.ndarray", "float", "int"], "output_types": ["tuple"]},
    "655": {"input_types": ["list", "int"], "output_types": ["list"]},
    "656": {"input_types": ["str", "SentimentIntensityAnalyzer"], "output_types": ["dict"]},
    "657": {"input_types": ["list", "list"], "output_types": ["Word2Vec"]},
    "658": {"input_types": ["list"], "output_types": ["pd.DataFrame"]},
    "659": {"input_types": ["list", "list", "list"], "output_types": ["Matplotlib figure"]},
    "660": {"input_types": ["list", "list", "list"], "output_types": ["matplotlib.figure.Figure"]},
    "661": {"input_types": ["list", "list", "list"], "output_types": ["Axes", "DataFrame"]},
    "662": {"input_types": ["list", "list", "list"], "output_types": ["Matplotlib figure"]},
    "663": {"input_types": ["list", "list", "list"], "output_types": ["matplotlib.figure.Figure"]},
    "664": {"input_types": ["pd.DataFrame"], "output_types": ["matplotlib.axes.Axes"]},
    "665": {"input_types": ["str", "str"], "output_types": ["str"]},
    "666": {"input_types": ["str", "dict"], "output_types": ["str"]},
    "667": {"input_types": ["dict", "int"], "output_types": ["list"]},
    "668": {"input_types": ["dict"], "output_types": ["list"]},
    "669": {"input_types": ["dict"], "output_types": ["tuple"]},
    "670": {"input_types": ["str", "dict"], "output_types": ["str"]},
    "671": {"input_types": ["str", "int"], "output_types": ["str"]},
    "672": {"input_types": ["str"], "output_types": ["str"]},
    "673": {"input_types": ["str", "int"], "output_types": ["int"]},
    "674": {"input_types": ["str"], "output_types": ["str"]},
    "675": {"input_types": ["str", "int"], "output_types": ["str"]},
    "676": {"input_types": ["pandas.DataFrame"], "output_types": ["pandas.DataFrame"]},
    "677": {"input_types": ["pandas.DataFrame"], "output_types": ["pandas.DataFrame"]},
    "678": {"input_types": ["str"], "output_types": ["pandas.DataFrame"]},
    "679": {"input_types": ["pandas.DataFrame"], "output_types": ["dict"]},
    "680": {"input_types": ["pandas.DataFrame", "list"], "output_types": ["pandas.DataFrame"]},
    "681": {"input_types": ["str", "str"], "output_types": ["DataFrame"]},
    "682": {"input_types": ["dict"], "output_types": ["dict"]},
    "683": {"input_types": ["str", "str"], "output_types": ["dict"]},
    "684": {"input_types": ["pd.DataFrame", "str"], "output_types": ["pd.DataFrame"]},
    "685": {"input_types": ["list"], "output_types": ["collections.Counter"]},
    "686": {"input_types": ["list"], "output_types": ["numpy.array"]},
    "687": {"input_types": ["list"], "output_types": ["tuple", "np.array", "int"]},
    "688": {"input_types": ["DataFrame"], "output_types": ["DataFrame"]},
    "689": {"input_types": ["DataFrame"], "output_types": ["dict"]},
    "690": {"input_types": ["DataFrame"], "output_types": ["LinearRegression"]},
    "691": {"input_types": ["DataFrame"], "output_types": ["np.array"]},
    "692": {"input_types": ["list"], "output_types": ["DataFrame"]},
    "693": {"input_types": ["list", "list"], "output_types": ["DataFrame"]},
    "694": {"input_types": ["tuple", "int"], "output_types": ["tuple"]},
    "695": {"input_types": ["list"], "output_types": ["ndarray"]},
    "696": {"input_types": ["int", "int"], "output_types": ["list"]},
    "697": {"input_types": ["pd.DataFrame"], "output_types": ["dict"]},
    "698": {"input_types": ["pd.DataFrame"], "output_types": ["tuple"]},
    "699": {"input_types": ["list", "list", "int", "int"], "output_types": ["tuple", "numpy.ndarray", "numpy.ndarray"]},
    "700": {"input_types": ["list", "list"], "output_types": ["pd.DataFrame"]},
    "701": {"input_types": ["pd.DataFrame", "str"], "output_types": ["float"]},
    "702": {"input_types": ["DataFrame"], "output_types": ["DataFrame"]},
    "703": {"input_types": ["list", "list"], "output_types": ["DataFrame"]},
    "704": {"input_types": ["list", "list", "float"], "output_types": ["list"]},
    "705": {"input_types": ["pd.DataFrame", "str", "float"], "output_types": ["bool"]},
    "706": {"input_types": ["numpy.array", "list", "str"], "output_types": ["float"]},
    "707": {"input_types": ["DataFrame"], "output_types": ["DataFrame"]},
    "708": {"input_types": ["str", "str", "str"], "output_types": ["str"]},
    "709": {"input_types": ["str", "int"], "output_types": ["str"]},
    "710": {"input_types": ["str"], "output_types": ["DataFrame"]},
    "711": {"input_types": ["str", "str"], "output_types": ["str"]},
    "712": {"input_types": ["str", "str", "str"], "output_types": ["int"]},
    "713": {"input_types": ["str", "list"], "output_types": ["list"]},
    "714": {"input_types": ["str"], "output_types": ["str"]},
    "715": {"input_types": ["str", "str"], "output_types": ["str"]},
    "716": {"input_types": ["str", "str"], "output_types": ["dict"]},
    "717": {"input_types": ["str", "str"], "output_types": ["object", "str"]},
    "718": {"input_types": ["str", "str"], "output_types": ["float", "float"]},
    "719": {"input_types": ["str", "str"], "output_types": ["int"]},
    "720": {"input_types": ["None"], "output_types": ["list"]},
    "721": {"input_types": ["str"], "output_types": ["tuple"]},
    "722": {"input_types": ["str"], "output_types": ["int"]},
    "723": {"input_types": ["str"], "output_types": ["str"]},
    "724": {"input_types": ["str"], "output_types": ["dict"]},
    "725": {"input_types": ["str", "str", "str"], "output_types": ["None"]},
    "726": {"input_types": ["str", "int"], "output_types": ["list"]},
    "727": {"input_types": ["str"], "output_types": ["np.ndarray"]},
    "728": {"input_types": ["str", "str", "str", "str"], "output_types": ["tuple", "list", "str"]},
    "729": {"input_types": ["list", "str"], "output_types": ["list"]},
    "730": {"input_types": ["datetime"], "output_types": ["datetime"]},
    "731": {"input_types": ["numpy array", "numpy array"], "output_types": ["tuple"]},
    "732": {"input_types": ["str"], "output_types": ["dict"]},
    "733": {"input_types": ["str"], "output_types": ["int"]},
    "734": {"input_types": ["str"], "output_types": ["dict"]},
    "735": {"input_types": ["list"], "output_types": ["dict"]},
    "736": {"input_types": ["list"], "output_types": ["int"]},
    "737": {"input_types": ["list"], "output_types": ["float"]},
    "738": {"input_types": ["list"], "output_types": ["float"]},
    "739": {"input_types": ["None"], "output_types": ["float"]},
    "740": {"input_types": ["dict"], "output_types": ["list"]},
    "741": {"input_types": ["dict"], "output_types": ["dict"]},
    "742": {"input_types": ["list"], "output_types": ["DataFrame"]},
    "743": {"input_types": ["str"], "output_types": ["dict"]},
    "744": {"input_types": ["str"], "output_types": ["DataFrame"]},
    "745": {"input_types": ["None"], "output_types": ["str"]},
    "746": {"input_types": ["DataFrame", "str", "array-like"], "output_types": ["LinearRegression"]},
    "747": {"input_types": ["str"], "output_types": ["int", "float"]},
    "748": {"input_types": ["pd.DataFrame", "numeric", "numeric"], "output_types": ["pd.DataFrame"]},
    "749": {"input_types": ["list"], "output_types": ["ndarray"]},
    "750": {
        "input_types": ["pd.DataFrame", "int", "int", "list"],
        "output_types": ["sm.regression.linear_model.RegressionResultsWrapper", "None"],
    },
    "751": {"input_types": ["list", "list", "int"], "output_types": ["dict"]},
    "752": {"input_types": ["DataFrame", "str", "int", "float"], "output_types": ["float"]},
    "753": {"input_types": ["int"], "output_types": ["float"]},
    "754": {"input_types": ["list"], "output_types": ["Series"]},
    "755": {"input_types": ["str"], "output_types": ["list"]},
    "756": {"input_types": ["str", "str", "list"], "output_types": ["int"]},
    "757": {"input_types": ["numpy.array"], "output_types": ["numpy.ndarray"]},
    "758": {"input_types": ["int", "list", "array", "list", "None"], "output_types": ["DataFrame"]},
    "759": {"input_types": ["str", "str", "str"], "output_types": ["list"]},
    "760": {"input_types": ["int", "int", "str", "list", "list", "int"], "output_types": ["DataFrame"]},
    "761": {"input_types": ["str"], "output_types": ["dict"]},
    "762": {"input_types": ["str", "str", "list", "str"], "output_types": ["str"]},
    "763": {"input_types": ["str", "str"], "output_types": ["dict"]},
    "764": {"input_types": ["str", "list", "list", "str", "int"], "output_types": ["str"]},
    "765": {"input_types": ["dict", "str"], "output_types": ["list"]},
    "766": {"input_types": ["str", "list"], "output_types": ["dict"]},
    "767": {"input_types": ["list"], "output_types": ["dict"]},
    "768": {"input_types": ["str"], "output_types": ["dict"]},
    "769": {"input_types": ["list"], "output_types": ["str"]},
    "770": {"input_types": ["int", "float", "int", "float"], "output_types": ["float", "LinearRegression"]},
    "771": {"input_types": ["str", "str"], "output_types": ["list"]},
    "772": {"input_types": ["int", "float", "float", "int"], "output_types": ["float"]},
    "773": {"input_types": ["None"], "output_types": ["None"]},
    "774": {"input_types": ["int", "int", "int", "int"], "output_types": ["float", "model"]},
    "775": {"input_types": ["str"], "output_types": ["dict"]},
    "776": {
        "input_types": ["str", "str", "str", "bool", "str", "str"],
        "output_types": ["DataFrame", "str", "LinearRegression"],
    },
    "777": {"input_types": ["str", "str"], "output_types": ["list"]},
    "778": {"input_types": ["list"], "output_types": ["dict"]},
    "779": {"input_types": ["str"], "output_types": ["tuple"]},
    "780": {"input_types": ["list", "str"], "output_types": ["DataFrame"]},
    "781": {"input_types": ["str"], "output_types": ["dict"]},
    "782": {"input_types": ["int", "str", "list", "int"], "output_types": ["DataFrame"]},
    "783": {"input_types": ["str", "str", "str"], "output_types": ["int"]},
    "784": {"input_types": ["int", "list", "list", "list", "str", "int"], "output_types": ["DataFrame"]},
    "785": {"input_types": ["str"], "output_types": ["str"]},
    "786": {"input_types": ["int", "list", "list", "str", "int"], "output_types": ["DataFrame"]},
    "787": {"input_types": ["numpy.array", "numpy.array"], "output_types": ["float"]},
    "788": {"input_types": ["pandas.DataFrame", "str", "int"], "output_types": ["float"]},
    "789": {"input_types": ["None"], "output_types": ["numpy.ndarray"]},
    "790": {"input_types": ["pandas.DataFrame", "str", "int"], "output_types": ["list"]},
    "791": {"input_types": ["list"], "output_types": ["collections.Counter"]},
    "792": {
        "input_types": ["pandas.DataFrame", "str", "str", "int"],
        "output_types": ["list[int]", "LinearRegression"],
    },
    "793": {"input_types": ["list"], "output_types": ["numpy.ndarray"]},
    "794": {"input_types": ["int", "int"], "output_types": ["str"]},
    "795": {"input_types": ["list"], "output_types": ["collections.deque"]},
    "796": {"input_types": ["str"], "output_types": ["list"]},
    "797": {"input_types": ["pandas.DataFrame"], "output_types": ["int"]},
    "798": {"input_types": ["str"], "output_types": ["str"]},
    "799": {"input_types": ["list", "int", "int"], "output_types": ["DataFrame", "list"]},
    "800": {"input_types": ["dict", "dict"], "output_types": ["Counter"]},
    "801": {"input_types": ["str"], "output_types": ["dict"]},
    "802": {"input_types": ["int"], "output_types": ["tuple"]},
    "803": {"input_types": ["str"], "output_types": ["DataFrame"]},
    "804": {"input_types": ["dict", "str", "str"], "output_types": ["bool"]},
    "805": {"input_types": ["dict", "str", "int"], "output_types": ["list", "int", "DataFrame"]},
    "806": {"input_types": ["str", "int"], "output_types": ["dict"]},
    "807": {"input_types": ["numpy.ndarray", "float"], "output_types": ["list", "float", "float"]},
    "808": {"input_types": ["str"], "output_types": ["Sentiment"]},
    "809": {"input_types": ["numpy array", "int"], "output_types": ["dict"]},
    "810": {"input_types": ["str", "str", "bool"], "output_types": ["list"]},
    "811": {"input_types": ["dictionary", "str", "int", "int"], "output_types": ["list", "DataFrame"]},
    "812": {"input_types": ["str", "str"], "output_types": ["str"]},
    "813": {"input_types": ["list", "int"], "output_types": ["Pandas DataFrame"]},
    "814": {"input_types": ["str", "str", "str"], "output_types": ["str"]},
    "815": {"input_types": ["dict", "int"], "output_types": ["np.array", "DataFrame"]},
    "816": {"input_types": ["None"], "output_types": ["tuple"]},
    "817": {"input_types": ["list", "str", "str"], "output_types": ["int"]},
    "818": {"input_types": ["str"], "output_types": ["list"]},
    "819": {"input_types": ["int", "float", "float", "float"], "output_types": ["list", "float"]},
    "820": {"input_types": ["int", "int"], "output_types": ["list"]},
    "821": {"input_types": ["float", "int"], "output_types": ["list"]},
    "822": {"input_types": ["int", "int"], "output_types": ["str"]},
    "823": {"input_types": ["int", "float"], "output_types": ["tuple"]},
    "824": {"input_types": ["str"], "output_types": ["tuple"]},
    "825": {"input_types": ["int", "int", "list"], "output_types": ["list"]},
    "826": {"input_types": ["str", "str", "str"], "output_types": ["int"]},
    "827": {"input_types": ["list"], "output_types": ["list"]},
    "828": {"input_types": ["str", "str"], "output_types": ["str"]},
    "829": {"input_types": ["DataFrame"], "output_types": ["dict"]},
    "830": {"input_types": ["str", "dict"], "output_types": ["tuple", "bool", "json"]},
    "831": {"input_types": ["int", "int", "int", "int"], "output_types": ["generator"]},
    "832": {"input_types": ["str", "object"], "output_types": ["bool"]},
    "833": {"input_types": ["int", "int", "int", "int"], "output_types": ["tuple", "int", "generator"]},
    "834": {"input_types": ["str"], "output_types": ["str"]},
    "835": {"input_types": ["int", "list", "list", "int"], "output_types": ["DataFrame"]},
    "836": {"input_types": ["str", "str", "str", "bool"], "output_types": ["dict"]},
    "837": {"input_types": ["int", "list", "list", "int"], "output_types": ["DataFrame"]},
    "838": {"input_types": ["pandas.Series"], "output_types": ["pandas.Series"]},
    "839": {"input_types": ["str", "int", "list", "list", "int"], "output_types": ["str"]},
    "840": {"input_types": ["str", "int", "int", "int"], "output_types": ["str"]},
    "841": {"input_types": ["str"], "output_types": ["dict"]},
    "842": {"input_types": ["str", "int", "list", "list", "int"], "output_types": ["str"]},
    "843": {"input_types": ["int"], "output_types": ["str"]},
    "844": {"input_types": ["str", "int", "int"], "output_types": ["str"]},
    "845": {"input_types": ["str", "str"], "output_types": ["tuple"]},
    "846": {"input_types": ["list", "str"], "output_types": ["collections.Counter"]},
    "847": {"input_types": ["str", "str"], "output_types": ["list"]},
    "848": {"input_types": ["list", "str", "int", "float"], "output_types": ["list", "float"]},
    "849": {"input_types": ["str"], "output_types": ["dict"]},
    "850": {"input_types": ["list", "list", "int"], "output_types": ["DataFrame"]},
    "851": {"input_types": ["str", "int"], "output_types": ["str"]},
    "852": {"input_types": ["int", "int", "int"], "output_types": ["list"]},
    "853": {"input_types": ["str"], "output_types": ["dict"]},
    "854": {"input_types": ["list"], "output_types": ["list", "list"]},
    "855": {"input_types": ["int", "int"], "output_types": ["dict"]},
    "856": {"input_types": ["tuple", "int", "int", "int"], "output_types": ["int", "np.array"]},
    "857": {"input_types": ["str", "str", "list"], "output_types": ["list"]},
    "858": {"input_types": ["int", "int"], "output_types": ["Counter"]},
    "859": {"input_types": ["None"], "output_types": ["tuple"]},
    "860": {"input_types": ["int", "str", "int"], "output_types": ["list"]},
    "861": {"input_types": ["list"], "output_types": ["list"]},
    "862": {"input_types": ["int", "int"], "output_types": ["defaultdict"]},
    "863": {"input_types": ["list"], "output_types": ["list"]},
    "864": {"input_types": ["list"], "output_types": ["DataFrame"]},
    "865": {"input_types": ["list"], "output_types": ["DataFrame"]},
    "866": {"input_types": ["list", "int", "int", "int"], "output_types": ["ndarray"]},
    "867": {"input_types": ["str", "str"], "output_types": ["tuple"]},
    "868": {"input_types": ["int", "list", "int"], "output_types": ["list"]},
    "869": {"input_types": ["int", "list", "range", "int"], "output_types": ["DataFrame"]},
    "870": {"input_types": ["list"], "output_types": ["DataFrame"]},
    "871": {"input_types": ["list", "str"], "output_types": ["list"]},
    "872": {"input_types": ["list"], "output_types": ["list"]},
    "873": {"input_types": ["list", "str", "list"], "output_types": ["str"]},
    "874": {"input_types": ["list"], "output_types": ["list"]},
    "875": {"input_types": ["list", "list", "bool", "tuple", "int"], "output_types": ["DataFrame"]},
    "876": {"input_types": ["dict", "str", "str"], "output_types": ["tuple", "dict", "list", "bool"]},
    "877": {"input_types": ["DataFrame", "int"], "output_types": ["DataFrame"]},
    "878": {
        "input_types": ["dictionary", "str", "float", "int"],
        "output_types": ["float", "RandomForestRegressor", "DataFrame"],
    },
    "879": {"input_types": ["pd.DataFrame", "str", "str"], "output_types": ["float"]},
    "880": {
        "input_types": ["pandas.DataFrame", "int", "int"],
        "output_types": ["numpy.ndarray", "sklearn.cluster.KMeans"],
    },
    "881": {"input_types": ["str", "str", "str", "int", "int"], "output_types": ["DataFrame"]},
    "882": {"input_types": ["str", "str", "str", "str"], "output_types": ["DataFrame"]},
    "883": {"input_types": ["pd.DataFrame", "str", "str", "str"], "output_types": ["bool"]},
    "884": {"input_types": ["pd.DataFrame", "list", "float", "float"], "output_types": ["float"]},
    "885": {"input_types": ["DataFrame", "str", "str", "str", "int"], "output_types": ["ndarray", "LinearRegression"]},
    "886": {"input_types": ["dict"], "output_types": ["pd.DataFrame", "pd.Series", "int", "None"]},
    "887": {"input_types": ["tuple", "int", "int"], "output_types": ["DataFrame"]},
    "888": {"input_types": ["str", "list"], "output_types": ["pd.DataFrame"]},
    "889": {"input_types": ["str", "str"], "output_types": ["pd.DataFrame"]},
    "890": {"input_types": ["str", "list", "int"], "output_types": ["tuple", "str", "DataFrame"]},
    "891": {"input_types": ["str", "str", "float", "int"], "output_types": ["tuple"]},
    "892": {"input_types": ["list"], "output_types": ["dict"]},
    "893": {"input_types": ["list"], "output_types": ["list", "time"]},
    "894": {"input_types": ["None"], "output_types": ["tuple"]},
    "895": {"input_types": ["None"], "output_types": ["tuple"]},
    "896": {"input_types": ["int", "int", "int"], "output_types": ["Counter"]},
    "897": {"input_types": ["int"], "output_types": ["tuple", "np.array", "matplotlib.Axes"]},
    "898": {"input_types": ["int", "int"], "output_types": ["Counter"]},
    "899": {"input_types": ["int", "int"], "output_types": ["np.array"]},
    "900": {"input_types": ["list"], "output_types": ["dict"]},
    "901": {"input_types": ["list"], "output_types": ["DataFrame"]},
    "902": {"input_types": ["list"], "output_types": ["dict"]},
    "903": {"input_types": ["list", "str"], "output_types": ["LinearRegression"]},
    "904": {"input_types": ["list", "list"], "output_types": ["Matplotlib Axes object"]},
    "905": {"input_types": ["str", "str"], "output_types": ["dict"]},
    "906": {"input_types": ["str", "str", "str"], "output_types": ["str"]},
    "907": {"input_types": ["str", "str", "str"], "output_types": ["bool"]},
    "908": {"input_types": ["str", "str"], "output_types": ["list"]},
    "909": {"input_types": ["list", "list"], "output_types": ["DataFrame"]},
    "910": {"input_types": ["list", "list", "list"], "output_types": ["Axes"]},
    "911": {"input_types": ["list"], "output_types": ["int"]},
    "912": {"input_types": ["list", "int"], "output_types": ["dict"]},
    "913": {"input_types": ["list", "int"], "output_types": ["dict"]},
    "914": {"input_types": ["DataFrame"], "output_types": ["tuple", "list", "Axes"]},
    "915": {
        "input_types": ["pandas.DataFrame", "float"],
        "output_types": ["tuple", "pandas.DataFrame", "matplotlib.axes._axes.Axes"],
    },
    "916": {"input_types": ["DataFrame"], "output_types": ["tuple"]},
    "917": {"input_types": ["pd.DataFrame"], "output_types": ["tuple"]},
    "918": {"input_types": ["dict", "dict"], "output_types": ["pd.DataFrame"]},
    "919": {"input_types": ["dict", "str"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "920": {"input_types": ["pandas.DataFrame"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "921": {"input_types": ["dict", "list"], "output_types": ["pandas.DataFrame"]},
    "922": {"input_types": ["pandas.DataFrame", "str"], "output_types": ["pandas.DataFrame"]},
    "923": {"input_types": ["list", "list", "int"], "output_types": ["DataFrame"]},
    "924": {"input_types": ["str", "str"], "output_types": ["pd.DataFrame"]},
    "925": {"input_types": ["int", "list"], "output_types": ["DataFrame"]},
    "926": {"input_types": ["str", "str", "str"], "output_types": ["pd.DataFrame"]},
    "927": {"input_types": ["str", "str"], "output_types": ["pd.DataFrame"]},
    "928": {"input_types": ["str"], "output_types": ["dict"]},
    "929": {"input_types": ["str"], "output_types": ["np.ndarray", "float"]},
    "930": {"input_types": ["str"], "output_types": ["list"]},
    "931": {"input_types": ["str"], "output_types": ["collections.defaultdict"]},
    "932": {"input_types": ["str"], "output_types": ["list"]},
    "933": {"input_types": ["str"], "output_types": ["list"]},
    "934": {"input_types": ["str"], "output_types": ["dict"]},
    "935": {"input_types": ["str"], "output_types": ["pandas.DataFrame"]},
    "936": {"input_types": ["list"], "output_types": ["Axes"]},
    "937": {"input_types": ["str"], "output_types": ["dict"]},
    "938": {"input_types": ["pandas.DataFrame"], "output_types": ["pandas.DataFrame"]},
    "939": {"input_types": ["str"], "output_types": ["list"]},
    "940": {"input_types": ["str"], "output_types": ["dict"]},
    "941": {"input_types": ["str", "int", "str", "int"], "output_types": ["tuple"]},
    "942": {"input_types": ["str", "int", "str", "list"], "output_types": ["DataFrame", "Axes"]},
    "943": {"input_types": ["str", "int", "str", "str"], "output_types": ["dict"]},
    "944": {"input_types": ["str", "int", "str", "int"], "output_types": ["tuple"]},
    "945": {"input_types": ["str", "int", "str", "array-like"], "output_types": ["numpy array"]},
    "946": {"input_types": ["int", "int", "int", "int"], "output_types": ["DataFrame"]},
    "947": {"input_types": ["int", "int", "datetime", "datetime"], "output_types": ["ndarray"]},
    "948": {"input_types": ["int", "int"], "output_types": ["ndarray"]},
    "949": {"input_types": ["int", "int", "int"], "output_types": ["DataFrame"]},
    "950": {"input_types": ["int", "int", "int"], "output_types": ["tuple"]},
    "951": {"input_types": ["list", "int"], "output_types": ["pd.DataFrame"]},
    "952": {"input_types": ["list", "int", "list", "int"], "output_types": ["pd.DataFrame"]},
    "953": {"input_types": ["list", "str", "int"], "output_types": ["list"]},
    "954": {"input_types": ["list", "int", "list"], "output_types": ["list"]},
    "955": {"input_types": ["list", "str"], "output_types": ["matplotlib.axes.Axes"]},
    "956": {"input_types": ["str", "int"], "output_types": ["str"]},
    "957": {"input_types": ["str"], "output_types": ["tuple"]},
    "958": {"input_types": ["str", "int"], "output_types": ["str"]},
    "959": {"input_types": ["str", "int"], "output_types": ["str"]},
    "960": {"input_types": ["str", "int"], "output_types": ["str"]},
    "961": {"input_types": ["str", "list", "bool"], "output_types": ["Counter"]},
    "962": {"input_types": ["str", "str"], "output_types": ["int"]},
    "963": {"input_types": ["str", "str", "str"], "output_types": ["str"]},
    "964": {"input_types": ["str", "str"], "output_types": ["int"]},
    "965": {"input_types": ["str", "str", "str"], "output_types": ["int"]},
    "966": {"input_types": ["pd.DataFrame"], "output_types": ["tuple"]},
    "967": {"input_types": ["function", "tuple", "int"], "output_types": ["matplotlib.axes.Axes"]},
    "968": {"input_types": ["dict"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "969": {"input_types": ["pandas.DataFrame"], "output_types": ["pandas.DataFrame"]},
    "970": {"input_types": ["numpy.ndarray"], "output_types": ["matplotlib.pyplot.Axes"]},
    "971": {"input_types": ["str"], "output_types": ["list", "tuple"]},
    "972": {"input_types": ["str", "str"], "output_types": ["list"]},
    "973": {"input_types": ["str", "str"], "output_types": ["list"]},
    "974": {"input_types": ["str", "str"], "output_types": ["tuple", "list"]},
    "975": {"input_types": ["int", "list", "int"], "output_types": ["pd.DataFrame"]},
    "976": {"input_types": ["ndarray", "int"], "output_types": ["DataFrame"]},
    "977": {"input_types": ["ndarray", "list", "int"], "output_types": ["Axes"]},
    "978": {"input_types": ["numpy.ndarray", "int"], "output_types": ["pandas.DataFrame"]},
    "979": {
        "input_types": ["numpy.ndarray", "numpy.ndarray", "list", "str", "int"],
        "output_types": ["sklearn.ensemble.RandomForestClassifier"],
    },
    "980": {"input_types": ["pandas.DataFrame"], "output_types": ["pandas.DataFrame", "matplotlib.figure.Figure"]},
    "981": {"input_types": ["str", "str", "int", "int"], "output_types": ["pandas.DataFrame", "plt.Axes"]},
    "982": {
        "input_types": ["pandas.DataFrame", "str", "int", "bool", "float", "str", "int"],
        "output_types": ["matplotlib.axes._axes.Axes"],
    },
    "983": {"input_types": ["pandas.DataFrame"], "output_types": ["tuple"]},
    "984": {"input_types": ["DataFrame", "str", "str"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "985": {"input_types": ["str", "str", "str"], "output_types": ["str", "pd.DataFrame"]},
    "986": {"input_types": ["str", "list"], "output_types": ["matplotlib.figure.Figure"]},
    "987": {"input_types": ["str", "str"], "output_types": ["tuple", "pd.Series", "pd.Series", "plt.Axes"]},
    "988": {"input_types": ["str", "list"], "output_types": ["dict"]},
    "989": {"input_types": ["int", "list", "int"], "output_types": ["tuple", "string", "dict"]},
    "990": {"input_types": ["str"], "output_types": ["dict"]},
    "991": {"input_types": ["int"], "output_types": ["str"]},
    "992": {"input_types": ["str", "str"], "output_types": ["str"]},
    "993": {"input_types": ["str"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "994": {"input_types": ["str", "str"], "output_types": ["list"]},
    "995": {"input_types": ["str", "str"], "output_types": ["tuple"]},
    "996": {"input_types": ["str", "str"], "output_types": ["str"]},
    "997": {"input_types": ["str"], "output_types": ["str"]},
    "998": {"input_types": ["str"], "output_types": ["bool"]},
    "999": {"input_types": ["str", "str", "str"], "output_types": ["dict"]},
    "1000": {"input_types": ["str"], "output_types": ["pandas.DataFrame"]},
    "1001": {"input_types": ["str"], "output_types": ["matplotlib.axes.Axes"]},
    "1002": {"input_types": ["list", "str"], "output_types": ["DataFrame", "Axes"]},
    "1003": {"input_types": ["str"], "output_types": ["pandas.DataFrame"]},
    "1004": {"input_types": ["str"], "output_types": ["tuple", "Counter", "Axes"]},
    "1005": {"input_types": ["str", "str", "str"], "output_types": ["str"]},
    "1006": {"input_types": ["str", "str"], "output_types": ["str"]},
    "1007": {"input_types": ["str"], "output_types": ["pd.DataFrame"]},
    "1008": {"input_types": ["str", "str"], "output_types": ["pd.DataFrame"]},
    "1009": {"input_types": ["str", "str"], "output_types": ["None"]},
    "1010": {"input_types": ["str"], "output_types": ["PIL.Image.Image"]},
    "1011": {"input_types": ["str", "str", "str"], "output_types": ["matplotlib.axes.Axes"]},
    "1012": {"input_types": ["str", "str"], "output_types": ["tuple"]},
    "1013": {"input_types": ["str", "str", "str"], "output_types": ["int"]},
    "1014": {"input_types": ["str"], "output_types": ["DataFrame", "Axes", "None"]},
    "1015": {"input_types": ["str", "str"], "output_types": ["int"]},
    "1016": {"input_types": ["str"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "1017": {"input_types": ["str", "str", "float", "int"], "output_types": ["str"]},
    "1018": {"input_types": ["str", "str", "bool"], "output_types": ["BeautifulSoup", "None"]},
    "1019": {"input_types": ["str", "str", "str"], "output_types": ["str"]},
    "1020": {"input_types": ["str", "str", "str"], "output_types": ["dict"]},
    "1021": {"input_types": ["str", "str"], "output_types": ["str", "bool"]},
    "1022": {
        "input_types": ["str", "str", "str"],
        "output_types": ["pandas", "os", "datetime.datetime", "pandas.errors.EmptyDataError"],
    },
    "1023": {"input_types": ["pd.DataFrame"], "output_types": ["plt.Axes"]},
    "1024": {"input_types": ["dict"], "output_types": ["DataFrame", "Axes", "None"]},
    "1025": {"input_types": ["dict"], "output_types": ["pandas.DataFrame", "matplotlib.Axes"]},
    "1026": {"input_types": ["dict"], "output_types": ["dict", "bool", "dict", "dict", "object", "object"]},
    "1027": {"input_types": ["str"], "output_types": ["str", "None"]},
    "1028": {"input_types": ["int", "int"], "output_types": ["str"]},
    "1029": {"input_types": ["int", "int"], "output_types": ["DataFrame"]},
    "1030": {"input_types": ["None"], "output_types": ["DataFrame"]},
    "1031": {"input_types": ["int"], "output_types": ["matplotlib.axes.Axes"]},
    "1032": {"input_types": ["int", "int"], "output_types": ["matplotlib.axes._axes.Axes", "None"]},
    "1033": {"input_types": ["None"], "output_types": ["tuple", "DataFrame", "Axes"]},
    "1034": {"input_types": ["pd.Series", "pd.Series"], "output_types": ["matplotlib.axes.Axes", "None", "float"]},
    "1035": {"input_types": ["pd.Series", "pd.Series"], "output_types": ["tuple"]},
    "1036": {"input_types": ["pd.Series", "pd.Series"], "output_types": ["matplotlib.Axes", "int"]},
    "1037": {
        "input_types": ["pandas.Series", "pandas.Series", "int"],
        "output_types": ["tuple", "ndarray", "matplotlib.axes.Axes"],
    },
    "1038": {"input_types": ["socket.socket"], "output_types": ["None"]},
    "1039": {"input_types": ["socket.socket", "str", "str", "int"], "output_types": ["str"]},
    "1040": {"input_types": ["str", "int", "int", "int"], "output_types": ["str"]},
    "1041": {"input_types": ["str"], "output_types": ["str"]},
    "1042": {"input_types": ["socket.socket"], "output_types": ["None"]},
    "1043": {"input_types": ["list"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "1044": {"input_types": ["str", "dict"], "output_types": ["DataFrame", "Axes"]},
    "1045": {"input_types": ["str"], "output_types": ["int"]},
    "1046": {"input_types": ["str"], "output_types": ["DataFrame"]},
    "1047": {"input_types": ["str"], "output_types": ["matplotlib.axes.Axes"]},
    "1048": {"input_types": ["str"], "output_types": ["matplotlib.axes.Axes"]},
    "1049": {"input_types": ["str"], "output_types": ["pd.DataFrame"]},
    "1050": {"input_types": ["str"], "output_types": ["list"]},
    "1051": {"input_types": ["dict"], "output_types": ["tuple", "matplotlib.axes._axes.Axes", "str"]},
    "1052": {"input_types": ["str", "str"], "output_types": ["matplotlib Axes object", "None"]},
    "1053": {"input_types": ["str", "str"], "output_types": ["matplotlib.axes.Axes", "None"]},
    "1054": {"input_types": ["str"], "output_types": ["tuple"]},
    "1055": {"input_types": ["list", "list"], "output_types": ["pandas.DataFrame"]},
    "1056": {"input_types": ["int"], "output_types": ["matplotlib.container.BarContainer"]},
    "1057": {"input_types": ["list", "list"], "output_types": ["pandas.DataFrame"]},
    "1058": {"input_types": ["int"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "1059": {"input_types": ["None"], "output_types": ["pandas.DataFrame"]},
    "1060": {"input_types": ["pd.DataFrame", "str"], "output_types": ["str", "plt.Axes"]},
    "1061": {"input_types": ["numpy.ndarray"], "output_types": ["tuple", "matplotlib.axes.Axes", "numpy.ndarray"]},
    "1062": {"input_types": ["numpy.ndarray"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "1063": {"input_types": ["numpy.ndarray"], "output_types": ["matplotlib.axes.Axes"]},
    "1064": {"input_types": ["numpy.array"], "output_types": ["matplotlib.axes.Axes"]},
    "1065": {"input_types": ["numpy.ndarray"], "output_types": ["matplotlib.axes.Axes"]},
    "1066": {
        "input_types": ["int", "int"],
        "output_types": ["numpy array", "numpy array", "matplotlib.axes._axes.Axes"],
    },
    "1067": {"input_types": ["str"], "output_types": ["dict"]},
    "1068": {"input_types": ["str", "str", "bool"], "output_types": ["pandas.DataFrame"]},
    "1069": {"input_types": ["pd.DataFrame"], "output_types": ["List[plt.Axes]"]},
    "1070": {"input_types": ["list"], "output_types": ["list"]},
    "1071": {"input_types": ["list"], "output_types": ["tuple"]},
    "1072": {"input_types": ["list"], "output_types": ["list"]},
    "1073": {"input_types": ["list", "str"], "output_types": ["matplotlib.axes._axes.Axes", "None"]},
    "1074": {"input_types": ["str", "str", "str"], "output_types": ["str"]},
    "1075": {"input_types": ["list"], "output_types": ["matplotlib.axes.Axes"]},
    "1076": {"input_types": ["list", "str"], "output_types": ["pandas.DataFrame"]},
    "1077": {"input_types": ["list", "str"], "output_types": ["float"]},
    "1078": {"input_types": ["numpy.ndarray"], "output_types": ["tuple", "bool", "matplotlib.axes.Axes"]},
    "1079": {"input_types": ["dict"], "output_types": ["dict", "matplotlib.axes._axes.Axes"]},
    "1080": {"input_types": ["str", "dict"], "output_types": ["float"]},
    "1081": {"input_types": ["dict"], "output_types": ["matplotlib.axes._axes.Axes"]},
    "1082": {"input_types": ["dict"], "output_types": ["float"]},
    "1083": {"input_types": ["dict"], "output_types": ["matplotlib.axes.Axes"]},
    "1084": {"input_types": ["str"], "output_types": ["pd.Series", "pd.Series", "list", "pd.DataFrame"]},
    "1085": {"input_types": ["str"], "output_types": ["list", "Axes"]},
    "1086": {"input_types": ["None"], "output_types": ["DataFrame"]},
    "1087": {"input_types": ["float", "float", "bool"], "output_types": ["float", "float", "list"]},
    "1088": {"input_types": ["numpy.ndarray"], "output_types": ["pandas.DataFrame"]},
    "1089": {"input_types": ["list"], "output_types": ["tuple"]},
    "1090": {"input_types": ["file"], "output_types": ["collections.Counter"]},
    "1091": {"input_types": ["str"], "output_types": ["list"]},
    "1092": {"input_types": ["str"], "output_types": ["list", "dict"]},
    "1093": {"input_types": ["str"], "output_types": ["list"]},
    "1094": {"input_types": ["str"], "output_types": ["list"]},
    "1095": {"input_types": ["str", "str"], "output_types": ["str"]},
    "1096": {"input_types": ["str", "str"], "output_types": ["str"]},
    "1097": {"input_types": ["str"], "output_types": ["str"]},
    "1098": {"input_types": ["str", "int"], "output_types": ["list"]},
    "1099": {"input_types": ["str"], "output_types": ["list"]},
    "1100": {"input_types": ["list"], "output_types": ["tuple"]},
    "1101": {"input_types": ["str"], "output_types": ["dict"]},
    "1102": {"input_types": ["str"], "output_types": ["dict"]},
    "1103": {"input_types": ["str", "str"], "output_types": ["str"]},
    "1104": {"input_types": ["str", "int"], "output_types": ["str"]},
    "1105": {"input_types": ["str", "str", "int"], "output_types": ["tuple"]},
    "1106": {"input_types": ["str"], "output_types": ["str"]},
    "1107": {"input_types": ["int", "str"], "output_types": ["str"]},
    "1108": {"input_types": ["list"], "output_types": ["dict"]},
    "1109": {"input_types": ["str"], "output_types": ["list"]},
    "1110": {"input_types": ["dict"], "output_types": ["dict"]},
    "1111": {"input_types": ["dict"], "output_types": ["dict"]},
    "1112": {"input_types": ["str"], "output_types": ["str"]},
    "1113": {"input_types": ["str", "str"], "output_types": ["dict"]},
    "1114": {"input_types": ["dict"], "output_types": ["dict"]},
    "1115": {"input_types": ["dict"], "output_types": ["list"]},
    "1116": {"input_types": ["dict"], "output_types": ["tuple"]},
    "1117": {"input_types": ["dict"], "output_types": ["str"]},
    "1118": {"input_types": ["str", "str"], "output_types": ["str"]},
    "1119": {"input_types": ["int", "str"], "output_types": ["str"]},
    "1120": {"input_types": ["str", "str"], "output_types": ["dict"]},
    "1121": {"input_types": ["str", "str"], "output_types": ["dict"]},
    "1122": {"input_types": ["str"], "output_types": ["dict"]},
    "1123": {"input_types": ["str"], "output_types": ["dict"]},
    "1124": {"input_types": ["str"], "output_types": ["str"]},
    "1125": {"input_types": ["str", "str"], "output_types": ["dict"]},
    "1126": {"input_types": ["str"], "output_types": ["str"]},
    "1127": {"input_types": ["str", "str"], "output_types": ["list"]},
    "1128": {"input_types": ["str", "str"], "output_types": ["str"]},
    "1129": {"input_types": ["str", "str", "str"], "output_types": ["str"]},
    "1130": {"input_types": ["str"], "output_types": ["str"]},
    "1131": {"input_types": ["str", "sqlite3.Cursor"], "output_types": ["int"]},
    "1132": {"input_types": ["str", "str", "int"], "output_types": ["str"]},
    "1133": {"input_types": ["str", "str", "str"], "output_types": ["str"]},
    "1134": {"input_types": ["str", "str", "str"], "output_types": ["list"]},
    "1135": {"input_types": ["str", "str"], "output_types": ["list"]},
    "1136": {"input_types": ["str", "str", "str", "dict"], "output_types": ["str"]},
    "1137": {"input_types": ["str", "str"], "output_types": ["list"]},
    "1138": {"input_types": ["numpy.array"], "output_types": ["tuple"]},
    "1139": {"input_types": ["dict"], "output_types": ["float"]},
}
